### ISSUE TITLE
per injury/condition setting

### ISSUE THREAD

**Issue by RenaudF** [FluffierThanThou/Pharmacist#1]
It would be nice to have the option to right-click an injury and select treat with (none/herbal/etc..) that overrides the default/template. This would add flexibility and make edge cases / crises a lot easier to manage.

Perhaps injury is too granular though, but some way to bypass the template on ad-hoc basis would be handy, in the same vein as prioritising jobs for pawns.

**Comment by FluffierThanThou** [comment]
the main problem with that is that injuries aren't actually treated one-by-one. When a pawn goes to tend, he looks at the patient and decides what medicine to use, and how much of it he'll need, and then he'll treat everything. 

This means that - even with pharmacist installed - the _worst_ injury and the _total_ bleedrate determine what medicine is used, for *all* injuries. Giving users the option to select per-condition medicine would give a false sense of control, as it would quite often be ignored.
