### ISSUE TITLE
Pharmacist is refusing to use industrial medicine to treat a dog's flu

### ISSUE THREAD

**Issue by shentino** [FluffierThanThou/Pharmacist#13]
Data:

* Pharmacist settings for animal: herbal for major and minor, industrial for life and operation
* Pharmacist immunity margin is set at 100 percent
* Animal patient's health tab lists spacer medicine, and spacer is also default medicine for animals
* Animal is sick with a flu at 1.6 percent, with immunity at 1
* Flu, IIRC, is a potentially fatal disease.
* Patient is Ricky, a male husky.

Problem:

My doctor, when ordered to treat the dog's flu, grabs an herbal medicine instead of an industrial medicine.

More information

* Changing the medicine type for major injuries changes what kind of medicine the doctor grabs

Suggested testing/experimentation

* Fiddle around with the animal/major slot and see what kind of medicine the doctor grabs when drafted/undrafted.

[pharmabug.rws.gz](https://github.com/FluffierThanThou/Pharmacist/files/2552907/pharmabug.rws.gz)

**Comment by shentino** [comment]
Looking at the source code it appears that the flu isn't getting recognized as a potentially fatal disease.

**Comment by FluffierThanThou** [comment]
The 'upgrade' to lethal doesn't kick in until severity has reached at least 10%, see 
https://github.com/FluffierThanThou/Pharmacist/blob/master/Source/Pharmacist/PharmacistUtility.cs#L67
and
https://github.com/FluffierThanThou/Pharmacist/blob/master/Source/Pharmacist/Constants.cs#L14

Wether or not that behaviour is desirable is another question, but the idea behind it is to prevent spending valuable medicine when a disease has just started.

**Comment by shentino** [comment]
If that was the case then I could just set the margin at 90 percent on my own, couldn't I?

At any rate, I've actually had some edge cases where even a 10 percent lag in applying top grade medicine was enough to get beaten by the clock and lose a patient to disease.

When I said "100" percent it was because I meant it, and I didn't want to take any chances.

One other serious problem is that applying the cheap medicine early on ALSO blocks the disease from being treated again until the next treatment window...by which time the disease itself may have progressed well beyond the original 10 percent mark.  Especially for fast progressing diseases like an infection.  Bad medicine means slower immunity, and if you have a fast disease your immunity may have fallen so far behind from starting with cheap medicine that by the time you apply the good stuff there won't be enough opportunity for the immunity to catch up before the disease hits 100.

So for the above reasons I actually do think the 10 percent "head start" is erroneous behavior.

**Comment by shentino** [comment]
At the very least, the 10 percent lower bound should be configurable if it isn't removed completely.

I'm a very paranoid doctor and have routinely resorted to micromanaging medicine choices when one of my colonists or even precious pets gets hit with a dangerous disease, but that paranoia has saved my patients in numerous cases when being slow with the good stuff would have cost them their life.

**Comment by shentino** [comment]
Finally i do want to point out that  I have seen numerous cases where the race between disease and immunity is quite close, so even a slight edge with the prompt application of good medicine is enough to tip the balance in my favor.

So I do feel fairly strongly about this issue.

**Comment by FluffierThanThou** [comment]
> So I do feel fairly strongly about this issue.  

I can see that! 😄 

I still maintain that for the majority of cases, not immediately going for the top medicine is the best call. I will concede that this isn't always the case, so I'll open up the threshold for editing (setting the default to what it is now).

**Comment by shentino** [comment]
That's an acceptable compromise indeed.

So why isn't the threshold redundant if you just set the margin to 90 percent?  I mean, the way it is now, is there any benefit to setting the margin higher than 90?

**Comment by FluffierThanThou** [comment]
> So why isn't the threshold redundant if you just set the margin to 90 percent?

Honestly, because that's (slightly) more complex, and I hadn't thought that anyone would push the margin to such extremes.

>  I mean, the way it is now, is there any benefit to setting the margin higher than 90?

No. Again, didn't think it would be used in this way.

**Comment by shentino** [comment]
I always have my margin set at a straight 100 because I have a zero tolerance policy for potentially fatal diseases ;)
