### ISSUE TITLE
Patient with one lethal wound and many bruises causes doctor to pick up assload of medicine.

### ISSUE THREAD

**Issue by shentino** [FluffierThanThou/Pharmacist#14]
I have a patient with an infection and many bruises, and Pharmacist configured to treat infections with industrial medicine.

My doctor winds up picking up 4 medicines and trying to use them to treat bruises.

Before the infeciton showed up, he used no medicine at all.

**Comment by FluffierThanThou** [comment]
yep, this is one of the caveats. Doctors treat _patients_, not _wounds_. What that means is that it's not really possible for me to know what medicine is going to be used to treat what injury, so I have to assume the worst case - in this case, that would be the infection.

That said, it's possible that the doctor is doing this _even though the infection was already tended previously_, which would be an oversight on my part. I'll have a look at that, I would appreciate it if you could confirm if this is indeed what is happening.

**Comment by shentino** [comment]
No, the infection wasn't tended yet, it just happened to be the worst injury, but there was only one of them.

I did manage to work around it with the help of another mod that allowed me to inventory-stash all the medicines but one and thus save the single dropped medicine for the infection...

...then the doctor himself went down for the count and I was forced to treat the infection with the crappy doctor I had left and he wound up dying anyway.

Such is life on rimworld lol.

What might help though is if you advocated having this mod's functionality merged into baseline rimworld.

In the meantime is there any way to intercept medical jobs so that wounds are treated one at a time?

**Comment by FluffierThanThou** [comment]
> In the meantime is there any way to intercept medical jobs so that wounds are treated one at a time?

Sure, but that's sacrificing a lot on efficiency. I thought about trying to split up treatments into batches per severity. In the end, I decided that this was already a complex enough system in vanilla, and then with several mods also touching on it, it would end up being a nightmare to get bug-free.

**Comment by shentino** [comment]
I beg to differ.

If the whole point is to conserve medicine for emergencies then stopping the doctor from blowing half a dozen kits on bruises just because the patient has a plague is well worth it.  Especially if you need those kits to keep treating the plague long after the bruises have been bandaged.  I've actually had cases where a greedy doctor hogged too much medicine and wound up coming up short later.

That said I think you can get the best of both worlds by toggling the behavior.

What if you added a switch/check box to allow this "one wound at a time" behavior to be selectively enabled at runtime?  That way nitpickers like me could be stingy, whereas those who have multiple mods could go without it.

For the record, Pharmacist has been a godsend.

**Comment by FluffierThanThou** [comment]
Oh don't get me wrong, I agree that the current behaviour of lumping everything together is far from ideal. What I was trying to point out was that treating _all_ wounds one at a time is also far from ideal, as that would imply doctors need to make a trip for each bruise separately. That quickly becomes ineffective, as there's more travel time, and the doctor wouldn't be able to use medicine to treat multiple minor wounds at once even if he wanted (and was allowed) to.

As far as I'm concerned, a good midway point would be to split wounds into batches by their severity. That means multiple bruises can still be treated together, but they wouldn't be treated together with a disease. 

The problem with that is that medical treatment is already quite a complex system, further complicated by the alterations that some other mods make - notably `smart medicine` and `mod medicine patch`. I'm currently only touching a well-defined section of the medical system; the two functions responsible for finding the best medicine. Altering how treatments are batched would mean extensive changes to a lot more of the medical system. 

I think I may have a word with the author of smarter medicine, see if this might not be better implemented from their end.

**Comment by shentino** [comment]
I already submitted a suggestion to change the medical api going forward in the core.

That said it's possible that you and the other medicine mod authors could hash things out and maybe even develop a common api not unlike hugslib that pharmacist and smart medicine could BOTH use.

If you and them depend on a shared mod and use it as a library it could enhance compatibility.

**Comment by shentino** [comment]
As for doctor travel time, it is a hassle, but they still have to make the first trip anyway.  For such purposes I've always found it handy to stash the medicine in the hospital itself.

**Comment by shentino** [comment]
> Oh don't get me wrong, I agree that the current behaviour of lumping everything together is far from ideal. What I was trying to point out was that treating _all_ wounds one at a time is also far from ideal, as that would imply doctors need to make a trip for each bruise separately. That quickly becomes ineffective, as there's more travel time, and the doctor wouldn't be able to use medicine to treat multiple minor wounds at once even if he wanted (and was allowed) to.
> 
> As far as I'm concerned, a good midway point would be to split wounds into batches by their severity. That means multiple bruises can still be treated together, but they wouldn't be treated together with a disease.
> 
> The problem with that is that medical treatment is already quite a complex system, further complicated by the alterations that some other mods make - notably `smart medicine` and `mod medicine patch`. I'm currently only touching a well-defined section of the medical system; the two functions responsible for finding the best medicine. Altering how treatments are batched would mean extensive changes to a lot more of the medical system.
> 
> I think I may have a word with the author of smarter medicine, see if this might not be better implemented from their end.

This is why stockpiles of medicine should be kept near the hospital. ;)
