### ISSUE TITLE
Pharmacist thinks artery blockage counts for medicine.

### ISSUE THREAD

**Issue by shentino** [FluffierThanThou/Pharmacist#15]
A colonist just got into a fight with a mad squirrel and got four small bleeding wounds.

However, she also has an artery blockage.

For some reason it's trying to grab industrial medicine, even though I have "minor wounds" set to no medicine.  This has happened a few times before, and I think it's tripping over untreatable ailments and treating them as injuries.  Other colonists without such things are being treated as expected.

**Comment by FluffierThanThou** [comment]
It appears I made a bad assumption in that only things that could be treated had the `Immunizable` comp, apparently that comp is used more generally for hediffs that can get worse over time. Go figure.

In addition, I never actually checked if a hediff was (currently or ever) treatable, which in turn mean that not only would conditions that had the immunizable hediff but weren't treatable (e.g. artery blockage) get treated with good medicine if they got severe enough, but diseases that _were already treated_ would also count for which medicine was used.

Both scenarios should now be fixed.
