### ISSUE TITLE
Edge Case with using Medicine we don't have

### ISSUE THREAD

**Issue by tunbridgep** [FluffierThanThou/Pharmacist#18]
So, I am using both Pharmacist and the Medical Tab mods.

I have selected for my Animals to use the Blue medicine or worse

In the Pharmacist tab I have life threatening illnesses set to use blue medicine for animals, and major injuries to use herbal medicine.

When my colonist went to heal the animal that was bleeding out, he instead used nothing. I have both blue and herbal stuff in my stockpile.

Maybe bleeding out is actually minor? (in which case I'm an idiot, ignore me).

**Comment by FluffierThanThou** [comment]
it depends on how quickly the animal is bleeding out, if death is expected within 5 hours, it counts as a major wound - otherwise it's considered minor. 

If you have a safe game with a similar situation set up, that would help greatly.

**Comment by FluffierThanThou** [comment]
sorry, gave you some bad info there. <6 hours is supposed to be life-threatening, <12 hours major.

**Comment by tunbridgep** [comment]
Right, the animal was going to bleed out in 11 hours.

Thanks for the info, this can be closed now.

My only real comment on this would be that perhaps the in-game tooltips should maybe point out the difference in major vs minor based on bleedout time
