### ISSUE TITLE
"Standing"/Infinite Job Loop

### ISSUE THREAD

**Issue by tobi1449** [FluffierThanThou/Pharmacist#7]
I'm experiencing the dreaded "Standing" bug in combination with the TendPatient Job and I strongly believe that your mod is the one responsible for it (yours is the only medical related mod I could find where it doesn't happen when I remove it).
I'm happy to provide my save (though it is heavily modded) or help you in any way to pinpoint what exactly is wrong.

**Comment by FluffierThanThou** [comment]
odd, I've never had that issue myself. If you're still running the mod and encountering the issue, an output_log.txt would be very useful.
