### ISSUE TITLE
window tab won't open

### ISSUE THREAD

**Issue by BryanAldrich** [FluffierThanThou/Pharmacist#8]
When using the 1.0 Pharmacist with the most recent 1.0 unstable, the tab won't open. The console log says "invalid cast" (among other things).

I've tried new/old games, even Pharmacist by itself, same result.

**Comment by BryanAldrich** [comment]
I broke down and pulled the source and recompiled it against the current build of RimWorld. it works with no changes.

**Comment by FluffierThanThou** [comment]
that's the problem with releasing mods for a fast-changing build, stuff
like this can happen. I don't have the time to keep them constantly
up-to-date, but I'll try and get out an updated build tonight. Thanks for
the investigative work! :D

**Comment by BryanAldrich** [comment]
FYI, i just found that Pharmacist on Rimworld on Linux doesn't work because the NAudio dlls are present. Apparently different ones are used there. Removing them from the folder resolves the issue.

Tested it on windows and linux. no errors.

**Comment by FluffierThanThou** [comment]
@BryanAldrich those really shouldn't be there to begin with, might have been my mistake, or you forgot to set the RimWorld assembly references to private. Anyway, both problems should be resolved now.
